[package]
name = "space_invaders"
version = "0.1.0"
authors = ["michele <michele.damico@gmail.com>"]

[dependencies]
rs8080 = { path="../" }
log="*"
simple_logger = "*"
minifb = "*"
structopt="*"

[dev-dependencies]
rstest = "0.3"
